#!/bin/bash

# format copied from https://github.com/junegunn/vader.vim#setting-up-isolated-testing-environment

vim -Nu <(cat << EOF
filetype off
set rtp+=~/.vim/bundle/vader.vim
set rtp+=.
set rtp+=./after
filetype plugin indent on
syntax enable
EOF) "+Vader! tests/*.vader"
